# config/strategies.yaml
strategies:
  - class: "DoubleMAStrategy"
    enable: false
    code_id: "NQ"
    interval: "D1"
    start_time: "2025-01-01 00:00:00"
    end_time: "2026-01-01 00:00:00"
    direction: "LONG"
    params:
      fast_window: 5
      slow_window: 20

  - class: "Break4Week"
    enable: false
    code_id: "NQ"
    interval: "M15"
    start_time: "2025-01-01 00:00:00"
    end_time: "2026-01-01 00:00:00"
    direction: "LONG"
    params:
      bar_count: 20
      can_open_begin: "08:00:00"
      can_open_end: "10:00:00"

  - class: "UTurnBottom"
    enable: true
    code_id: "NQ"
    interval: "M15"
    direction: "LONG"
    use_enriched: true
    start_time: "2025-01-01 00:00:00"
    end_time:   "2026-01-01 00:00:00"
    params:
      iv: 0.24
      risk_free_rate: 0.04
      option_days: 14