# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.9
#
# <auto-generated>
#
# Generated from file `QStruc.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module IBTrader
_M_IBTrader = Ice.openModule('IBTrader')
__name__ = 'IBTrader'

if 'IExchangePl' not in _M_IBTrader.__dict__:
    _M_IBTrader.IExchangePl = Ice.createTempClass()
    class IExchangePl(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    IExchangePl.SMART = IExchangePl("SMART", 0)
    IExchangePl.SEHK = IExchangePl("SEHK", 1)
    IExchangePl.NYSE = IExchangePl("NYSE", 2)
    IExchangePl.NASDAQ = IExchangePl("NASDAQ", 3)
    IExchangePl.ARCA = IExchangePl("ARCA", 4)
    IExchangePl._enumerators = { 0:IExchangePl.SMART, 1:IExchangePl.SEHK, 2:IExchangePl.NYSE, 3:IExchangePl.NASDAQ, 4:IExchangePl.ARCA }

    _M_IBTrader._t_IExchangePl = IcePy.defineEnum('::IBTrader::IExchangePl', IExchangePl, (), IExchangePl._enumerators)

    _M_IBTrader.IExchangePl = IExchangePl
    del IExchangePl

if 'IMoney' not in _M_IBTrader.__dict__:
    _M_IBTrader.IMoney = Ice.createTempClass()
    class IMoney(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    IMoney.RMB = IMoney("RMB", 0)
    IMoney.USD = IMoney("USD", 1)
    IMoney.HKD = IMoney("HKD", 2)
    IMoney.GBP = IMoney("GBP", 3)
    IMoney.JPY = IMoney("JPY", 4)
    IMoney.CAD = IMoney("CAD", 5)
    IMoney.AUD = IMoney("AUD", 6)
    IMoney.EUR = IMoney("EUR", 7)
    IMoney.KRW = IMoney("KRW", 8)
    IMoney._enumerators = { 0:IMoney.RMB, 1:IMoney.USD, 2:IMoney.HKD, 3:IMoney.GBP, 4:IMoney.JPY, 5:IMoney.CAD, 6:IMoney.AUD, 7:IMoney.EUR, 8:IMoney.KRW }

    _M_IBTrader._t_IMoney = IcePy.defineEnum('::IBTrader::IMoney', IMoney, (), IMoney._enumerators)

    _M_IBTrader.IMoney = IMoney
    del IMoney

if 'ITimePair' not in _M_IBTrader.__dict__:
    _M_IBTrader.ITimePair = Ice.createTempClass()
    class ITimePair(object):
        def __init__(self, beginPos=0, endPos=0):
            self.beginPos = beginPos
            self.endPos = endPos

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.beginPos)
            _h = 5 * _h + Ice.getHash(self.endPos)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_IBTrader.ITimePair):
                return NotImplemented
            else:
                if self.beginPos is None or other.beginPos is None:
                    if self.beginPos != other.beginPos:
                        return (-1 if self.beginPos is None else 1)
                else:
                    if self.beginPos < other.beginPos:
                        return -1
                    elif self.beginPos > other.beginPos:
                        return 1
                if self.endPos is None or other.endPos is None:
                    if self.endPos != other.endPos:
                        return (-1 if self.endPos is None else 1)
                else:
                    if self.endPos < other.endPos:
                        return -1
                    elif self.endPos > other.endPos:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_ITimePair)

        __repr__ = __str__

    _M_IBTrader._t_ITimePair = IcePy.defineStruct('::IBTrader::ITimePair', ITimePair, (), (
        ('beginPos', (), IcePy._t_long),
        ('endPos', (), IcePy._t_long)
    ))

    _M_IBTrader.ITimePair = ITimePair
    del ITimePair

if '_t_ITimePairs' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_ITimePairs = IcePy.defineSequence('::IBTrader::ITimePairs', (), _M_IBTrader._t_ITimePair)

if 'IQuery' not in _M_IBTrader.__dict__:
    _M_IBTrader.IQuery = Ice.createTempClass()
    class IQuery(object):
        def __init__(self, byReqType=0, dwSubscribeNum=0, tTime=0, timePair=Ice._struct_marker):
            self.byReqType = byReqType
            self.dwSubscribeNum = dwSubscribeNum
            self.tTime = tTime
            if timePair is Ice._struct_marker:
                self.timePair = _M_IBTrader.ITimePair()
            else:
                self.timePair = timePair

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.byReqType)
            _h = 5 * _h + Ice.getHash(self.dwSubscribeNum)
            _h = 5 * _h + Ice.getHash(self.tTime)
            _h = 5 * _h + Ice.getHash(self.timePair)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_IBTrader.IQuery):
                return NotImplemented
            else:
                if self.byReqType is None or other.byReqType is None:
                    if self.byReqType != other.byReqType:
                        return (-1 if self.byReqType is None else 1)
                else:
                    if self.byReqType < other.byReqType:
                        return -1
                    elif self.byReqType > other.byReqType:
                        return 1
                if self.dwSubscribeNum is None or other.dwSubscribeNum is None:
                    if self.dwSubscribeNum != other.dwSubscribeNum:
                        return (-1 if self.dwSubscribeNum is None else 1)
                else:
                    if self.dwSubscribeNum < other.dwSubscribeNum:
                        return -1
                    elif self.dwSubscribeNum > other.dwSubscribeNum:
                        return 1
                if self.tTime is None or other.tTime is None:
                    if self.tTime != other.tTime:
                        return (-1 if self.tTime is None else 1)
                else:
                    if self.tTime < other.tTime:
                        return -1
                    elif self.tTime > other.tTime:
                        return 1
                if self.timePair is None or other.timePair is None:
                    if self.timePair != other.timePair:
                        return (-1 if self.timePair is None else 1)
                else:
                    if self.timePair < other.timePair:
                        return -1
                    elif self.timePair > other.timePair:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IQuery)

        __repr__ = __str__

    _M_IBTrader._t_IQuery = IcePy.defineStruct('::IBTrader::IQuery', IQuery, (), (
        ('byReqType', (), IcePy._t_byte),
        ('dwSubscribeNum', (), IcePy._t_long),
        ('tTime', (), IcePy._t_long),
        ('timePair', (), _M_IBTrader._t_ITimePair)
    ))

    _M_IBTrader.IQuery = IQuery
    del IQuery

if 'IContract' not in _M_IBTrader.__dict__:
    _M_IBTrader.IContract = Ice.createTempClass()
    class IContract(object):
        def __init__(self, codeId="", des="", exchangePl=_M_IBTrader.IExchangePl.SMART, primaryExchangePl=_M_IBTrader.IExchangePl.NASDAQ, currencyID=_M_IBTrader.IMoney.USD, decDigits=0, minMove=0):
            self.codeId = codeId
            self.des = des
            self.exchangePl = exchangePl
            self.primaryExchangePl = primaryExchangePl
            self.currencyID = currencyID
            self.decDigits = decDigits
            self.minMove = minMove

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IContract):
                return NotImplemented
            else:
                if self.codeId != other.codeId:
                    return False
                if self.des != other.des:
                    return False
                if self.exchangePl != other.exchangePl:
                    return False
                if self.primaryExchangePl != other.primaryExchangePl:
                    return False
                if self.currencyID != other.currencyID:
                    return False
                if self.decDigits != other.decDigits:
                    return False
                if self.minMove != other.minMove:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IContract)

        __repr__ = __str__

    _M_IBTrader._t_IContract = IcePy.defineStruct('::IBTrader::IContract', IContract, (), (
        ('codeId', (), IcePy._t_string),
        ('des', (), IcePy._t_string),
        ('exchangePl', (), _M_IBTrader._t_IExchangePl),
        ('primaryExchangePl', (), _M_IBTrader._t_IExchangePl),
        ('currencyID', (), _M_IBTrader._t_IMoney),
        ('decDigits', (), IcePy._t_int),
        ('minMove', (), IcePy._t_double)
    ))

    _M_IBTrader.IContract = IContract
    del IContract

if '_t_IContracts' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IContracts = IcePy.defineSequence('::IBTrader::IContracts', (), _M_IBTrader._t_IContract)

if 'IBidAsk' not in _M_IBTrader.__dict__:
    _M_IBTrader.IBidAsk = Ice.createTempClass()
    class IBidAsk(object):
        def __init__(self, bid=0, bidVol=0, ask=0, askVol=0):
            self.bid = bid
            self.bidVol = bidVol
            self.ask = ask
            self.askVol = askVol

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IBidAsk):
                return NotImplemented
            else:
                if self.bid != other.bid:
                    return False
                if self.bidVol != other.bidVol:
                    return False
                if self.ask != other.ask:
                    return False
                if self.askVol != other.askVol:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IBidAsk)

        __repr__ = __str__

    _M_IBTrader._t_IBidAsk = IcePy.defineStruct('::IBTrader::IBidAsk', IBidAsk, (), (
        ('bid', (), IcePy._t_double),
        ('bidVol', (), IcePy._t_int),
        ('ask', (), IcePy._t_double),
        ('askVol', (), IcePy._t_int)
    ))

    _M_IBTrader.IBidAsk = IBidAsk
    del IBidAsk

if '_t_IBidAsks' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IBidAsks = IcePy.defineSequence('::IBTrader::IBidAsks', (), _M_IBTrader._t_IBidAsk)

if 'ITick' not in _M_IBTrader.__dict__:
    _M_IBTrader.ITick = Ice.createTempClass()
    class ITick(object):
        def __init__(self, codeId="", time=0, bidAsks=None, open=0, last=0, vol=0, totalVol=0, turnOver=0, timeStamp=0):
            self.codeId = codeId
            self.time = time
            self.bidAsks = bidAsks
            self.open = open
            self.last = last
            self.vol = vol
            self.totalVol = totalVol
            self.turnOver = turnOver
            self.timeStamp = timeStamp

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.ITick):
                return NotImplemented
            else:
                if self.codeId != other.codeId:
                    return False
                if self.time != other.time:
                    return False
                if self.bidAsks != other.bidAsks:
                    return False
                if self.open != other.open:
                    return False
                if self.last != other.last:
                    return False
                if self.vol != other.vol:
                    return False
                if self.totalVol != other.totalVol:
                    return False
                if self.turnOver != other.turnOver:
                    return False
                if self.timeStamp != other.timeStamp:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_ITick)

        __repr__ = __str__

    _M_IBTrader._t_ITick = IcePy.defineStruct('::IBTrader::ITick', ITick, (), (
        ('codeId', (), IcePy._t_string),
        ('time', (), IcePy._t_long),
        ('bidAsks', (), _M_IBTrader._t_IBidAsks),
        ('open', (), IcePy._t_double),
        ('last', (), IcePy._t_double),
        ('vol', (), IcePy._t_int),
        ('totalVol', (), IcePy._t_int),
        ('turnOver', (), IcePy._t_double),
        ('timeStamp', (), IcePy._t_long)
    ))

    _M_IBTrader.ITick = ITick
    del ITick

if '_t_ITicks' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_ITicks = IcePy.defineSequence('::IBTrader::ITicks', (), _M_IBTrader._t_ITick)

if 'ITimeType' not in _M_IBTrader.__dict__:
    _M_IBTrader.ITimeType = Ice.createTempClass()
    class ITimeType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    ITimeType.S15 = ITimeType("S15", 0)
    ITimeType.M1 = ITimeType("M1", 1)
    ITimeType.M5 = ITimeType("M5", 2)
    ITimeType.M15 = ITimeType("M15", 3)
    ITimeType.M30 = ITimeType("M30", 4)
    ITimeType.H1 = ITimeType("H1", 5)
    ITimeType.D1 = ITimeType("D1", 6)
    ITimeType._enumerators = { 0:ITimeType.S15, 1:ITimeType.M1, 2:ITimeType.M5, 3:ITimeType.M15, 4:ITimeType.M30, 5:ITimeType.H1, 6:ITimeType.D1 }

    _M_IBTrader._t_ITimeType = IcePy.defineEnum('::IBTrader::ITimeType', ITimeType, (), ITimeType._enumerators)

    _M_IBTrader.ITimeType = ITimeType
    del ITimeType

if 'IQKey' not in _M_IBTrader.__dict__:
    _M_IBTrader.IQKey = Ice.createTempClass()
    class IQKey(object):
        def __init__(self, codeId="", timeType=_M_IBTrader.ITimeType.D1):
            self.codeId = codeId
            self.timeType = timeType

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.codeId)
            _h = 5 * _h + Ice.getHash(self.timeType)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_IBTrader.IQKey):
                return NotImplemented
            else:
                if self.codeId is None or other.codeId is None:
                    if self.codeId != other.codeId:
                        return (-1 if self.codeId is None else 1)
                else:
                    if self.codeId < other.codeId:
                        return -1
                    elif self.codeId > other.codeId:
                        return 1
                if self.timeType is None or other.timeType is None:
                    if self.timeType != other.timeType:
                        return (-1 if self.timeType is None else 1)
                else:
                    if self.timeType < other.timeType:
                        return -1
                    elif self.timeType > other.timeType:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IQKey)

        __repr__ = __str__

    _M_IBTrader._t_IQKey = IcePy.defineStruct('::IBTrader::IQKey', IQKey, (), (
        ('codeId', (), IcePy._t_string),
        ('timeType', (), _M_IBTrader._t_ITimeType)
    ))

    _M_IBTrader.IQKey = IQKey
    del IQKey

if 'IKLine' not in _M_IBTrader.__dict__:
    _M_IBTrader.IKLine = Ice.createTempClass()
    class IKLine(object):
        def __init__(self, time=0, close=0.0, open=0.0, high=0.0, low=0.0, vol=0):
            self.time = time
            self.close = close
            self.open = open
            self.high = high
            self.low = low
            self.vol = vol

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IKLine):
                return NotImplemented
            else:
                if self.time != other.time:
                    return False
                if self.close != other.close:
                    return False
                if self.open != other.open:
                    return False
                if self.high != other.high:
                    return False
                if self.low != other.low:
                    return False
                if self.vol != other.vol:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IKLine)

        __repr__ = __str__

    _M_IBTrader._t_IKLine = IcePy.defineStruct('::IBTrader::IKLine', IKLine, (), (
        ('time', (), IcePy._t_long),
        ('close', (), IcePy._t_double),
        ('open', (), IcePy._t_double),
        ('high', (), IcePy._t_double),
        ('low', (), IcePy._t_double),
        ('vol', (), IcePy._t_long)
    ))

    _M_IBTrader.IKLine = IKLine
    del IKLine

if '_t_IKLines' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IKLines = IcePy.defineSequence('::IBTrader::IKLines', (), _M_IBTrader._t_IKLine)

if 'IKLinePair' not in _M_IBTrader.__dict__:
    _M_IBTrader.IKLinePair = Ice.createTempClass()
    class IKLinePair(object):
        def __init__(self, first=Ice._struct_marker, second=Ice._struct_marker):
            if first is Ice._struct_marker:
                self.first = _M_IBTrader.IKLine()
            else:
                self.first = first
            if second is Ice._struct_marker:
                self.second = _M_IBTrader.IKLine()
            else:
                self.second = second

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IKLinePair):
                return NotImplemented
            else:
                if self.first != other.first:
                    return False
                if self.second != other.second:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IKLinePair)

        __repr__ = __str__

    _M_IBTrader._t_IKLinePair = IcePy.defineStruct('::IBTrader::IKLinePair', IKLinePair, (), (
        ('first', (), _M_IBTrader._t_IKLine),
        ('second', (), _M_IBTrader._t_IKLine)
    ))

    _M_IBTrader.IKLinePair = IKLinePair
    del IKLinePair

if '_t_IKLinePairs' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IKLinePairs = IcePy.defineSequence('::IBTrader::IKLinePairs', (), _M_IBTrader._t_IKLinePair)

if 'IAvgValue' not in _M_IBTrader.__dict__:
    _M_IBTrader.IAvgValue = Ice.createTempClass()
    class IAvgValue(object):
        def __init__(self, time=0, v5=0.0, v20=0.0, v60=0.0, v200=0.0):
            self.time = time
            self.v5 = v5
            self.v20 = v20
            self.v60 = v60
            self.v200 = v200

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IAvgValue):
                return NotImplemented
            else:
                if self.time != other.time:
                    return False
                if self.v5 != other.v5:
                    return False
                if self.v20 != other.v20:
                    return False
                if self.v60 != other.v60:
                    return False
                if self.v200 != other.v200:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IAvgValue)

        __repr__ = __str__

    _M_IBTrader._t_IAvgValue = IcePy.defineStruct('::IBTrader::IAvgValue', IAvgValue, (), (
        ('time', (), IcePy._t_long),
        ('v5', (), IcePy._t_double),
        ('v20', (), IcePy._t_double),
        ('v60', (), IcePy._t_double),
        ('v200', (), IcePy._t_double)
    ))

    _M_IBTrader.IAvgValue = IAvgValue
    del IAvgValue

if '_t_IAvgValues' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IAvgValues = IcePy.defineSequence('::IBTrader::IAvgValues', (), _M_IBTrader._t_IAvgValue)

if 'IMacdValue' not in _M_IBTrader.__dict__:
    _M_IBTrader.IMacdValue = Ice.createTempClass()
    class IMacdValue(object):
        def __init__(self, time=0, emaShort=0.0, emaLong=0.0, dif=0.0, dea=0.0, macd=0.0):
            self.time = time
            self.emaShort = emaShort
            self.emaLong = emaLong
            self.dif = dif
            self.dea = dea
            self.macd = macd

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IMacdValue):
                return NotImplemented
            else:
                if self.time != other.time:
                    return False
                if self.emaShort != other.emaShort:
                    return False
                if self.emaLong != other.emaLong:
                    return False
                if self.dif != other.dif:
                    return False
                if self.dea != other.dea:
                    return False
                if self.macd != other.macd:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IMacdValue)

        __repr__ = __str__

    _M_IBTrader._t_IMacdValue = IcePy.defineStruct('::IBTrader::IMacdValue', IMacdValue, (), (
        ('time', (), IcePy._t_long),
        ('emaShort', (), IcePy._t_double),
        ('emaLong', (), IcePy._t_double),
        ('dif', (), IcePy._t_double),
        ('dea', (), IcePy._t_double),
        ('macd', (), IcePy._t_double)
    ))

    _M_IBTrader.IMacdValue = IMacdValue
    del IMacdValue

if '_t_IMacdValues' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IMacdValues = IcePy.defineSequence('::IBTrader::IMacdValues', (), _M_IBTrader._t_IMacdValue)

if 'IDivType' not in _M_IBTrader.__dict__:
    _M_IBTrader.IDivType = Ice.createTempClass()
    class IDivType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    IDivType.NORMAL = IDivType("NORMAL", 0)
    IDivType.TOP = IDivType("TOP", 1)
    IDivType.BOTTOM = IDivType("BOTTOM", 2)
    IDivType.TOPSUB = IDivType("TOPSUB", 3)
    IDivType.BOTTOMSUB = IDivType("BOTTOMSUB", 4)
    IDivType._enumerators = { 0:IDivType.NORMAL, 1:IDivType.TOP, 2:IDivType.BOTTOM, 3:IDivType.TOPSUB, 4:IDivType.BOTTOMSUB }

    _M_IBTrader._t_IDivType = IcePy.defineEnum('::IBTrader::IDivType', IDivType, (), IDivType._enumerators)

    _M_IBTrader.IDivType = IDivType
    del IDivType

if '_t_IDivTypes' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IDivTypes = IcePy.defineSequence('::IBTrader::IDivTypes', (), _M_IBTrader._t_IDivType)

if 'IDivTypeValue' not in _M_IBTrader.__dict__:
    _M_IBTrader.IDivTypeValue = Ice.createTempClass()
    class IDivTypeValue(object):
        def __init__(self, time=0, divType=_M_IBTrader.IDivType.NORMAL, isUTurn=False):
            self.time = time
            self.divType = divType
            self.isUTurn = isUTurn

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.time)
            _h = 5 * _h + Ice.getHash(self.divType)
            _h = 5 * _h + Ice.getHash(self.isUTurn)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_IBTrader.IDivTypeValue):
                return NotImplemented
            else:
                if self.time is None or other.time is None:
                    if self.time != other.time:
                        return (-1 if self.time is None else 1)
                else:
                    if self.time < other.time:
                        return -1
                    elif self.time > other.time:
                        return 1
                if self.divType is None or other.divType is None:
                    if self.divType != other.divType:
                        return (-1 if self.divType is None else 1)
                else:
                    if self.divType < other.divType:
                        return -1
                    elif self.divType > other.divType:
                        return 1
                if self.isUTurn is None or other.isUTurn is None:
                    if self.isUTurn != other.isUTurn:
                        return (-1 if self.isUTurn is None else 1)
                else:
                    if self.isUTurn < other.isUTurn:
                        return -1
                    elif self.isUTurn > other.isUTurn:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IDivTypeValue)

        __repr__ = __str__

    _M_IBTrader._t_IDivTypeValue = IcePy.defineStruct('::IBTrader::IDivTypeValue', IDivTypeValue, (), (
        ('time', (), IcePy._t_long),
        ('divType', (), _M_IBTrader._t_IDivType),
        ('isUTurn', (), IcePy._t_bool)
    ))

    _M_IBTrader.IDivTypeValue = IDivTypeValue
    del IDivTypeValue

if '_t_IDivTypeValues' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IDivTypeValues = IcePy.defineSequence('::IBTrader::IDivTypeValues', (), _M_IBTrader._t_IDivTypeValue)

if 'IAtrValue' not in _M_IBTrader.__dict__:
    _M_IBTrader.IAtrValue = Ice.createTempClass()
    class IAtrValue(object):
        def __init__(self, time=0, thisAtr=0, avgAtr=0):
            self.time = time
            self.thisAtr = thisAtr
            self.avgAtr = avgAtr

        def __eq__(self, other):
            if other is None:
                return False
            elif not isinstance(other, _M_IBTrader.IAtrValue):
                return NotImplemented
            else:
                if self.time != other.time:
                    return False
                if self.thisAtr != other.thisAtr:
                    return False
                if self.avgAtr != other.avgAtr:
                    return False
                return True

        def __ne__(self, other):
            return not self.__eq__(other)

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IAtrValue)

        __repr__ = __str__

    _M_IBTrader._t_IAtrValue = IcePy.defineStruct('::IBTrader::IAtrValue', IAtrValue, (), (
        ('time', (), IcePy._t_long),
        ('thisAtr', (), IcePy._t_double),
        ('avgAtr', (), IcePy._t_double)
    ))

    _M_IBTrader.IAtrValue = IAtrValue
    del IAtrValue

if '_t_IAtrValues' not in _M_IBTrader.__dict__:
    _M_IBTrader._t_IAtrValues = IcePy.defineSequence('::IBTrader::IAtrValues', (), _M_IBTrader._t_IAtrValue)

# End of module IBTrader
