# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.9
#
# <auto-generated>
#
# Generated from file `QDatabase.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy
import QStruc_ice

# Included module IBTrader
_M_IBTrader = Ice.openModule('IBTrader')

# Start of module IBTrader
__name__ = 'IBTrader'

_M_IBTrader._t_IQDatabase = IcePy.defineValue('::IBTrader::IQDatabase', Ice.Value, -1, (), False, True, None, ())

if 'IQDatabasePrx' not in _M_IBTrader.__dict__:
    _M_IBTrader.IQDatabasePrx = Ice.createTempClass()
    class IQDatabasePrx(Ice.ObjectPrx):

        def IdlCount(self, context=None):
            return _M_IBTrader.IQDatabase._op_IdlCount.invoke(self, ((), context))

        def IdlCountAsync(self, context=None):
            return _M_IBTrader.IQDatabase._op_IdlCount.invokeAsync(self, ((), context))

        def begin_IdlCount(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_IdlCount.begin(self, ((), _response, _ex, _sent, context))

        def end_IdlCount(self, _r):
            return _M_IBTrader.IQDatabase._op_IdlCount.end(self, _r)

        def IsAllIdle(self, context=None):
            return _M_IBTrader.IQDatabase._op_IsAllIdle.invoke(self, ((), context))

        def IsAllIdleAsync(self, context=None):
            return _M_IBTrader.IQDatabase._op_IsAllIdle.invokeAsync(self, ((), context))

        def begin_IsAllIdle(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_IsAllIdle.begin(self, ((), _response, _ex, _sent, context))

        def end_IsAllIdle(self, _r):
            return _M_IBTrader.IQDatabase._op_IsAllIdle.end(self, _r)

        def TaskCount(self, context=None):
            return _M_IBTrader.IQDatabase._op_TaskCount.invoke(self, ((), context))

        def TaskCountAsync(self, context=None):
            return _M_IBTrader.IQDatabase._op_TaskCount.invokeAsync(self, ((), context))

        def begin_TaskCount(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_TaskCount.begin(self, ((), _response, _ex, _sent, context))

        def end_TaskCount(self, _r):
            return _M_IBTrader.IQDatabase._op_TaskCount.end(self, _r)

        def UpdateTickToDB(self, tick, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateTickToDB.invoke(self, ((tick, ), context))

        def UpdateTickToDBAsync(self, tick, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateTickToDB.invokeAsync(self, ((tick, ), context))

        def begin_UpdateTickToDB(self, tick, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateTickToDB.begin(self, ((tick, ), _response, _ex, _sent, context))

        def end_UpdateTickToDB(self, _r):
            return _M_IBTrader.IQDatabase._op_UpdateTickToDB.end(self, _r)

        def GetLastUpdateTick(self, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastUpdateTick.invoke(self, ((), context))

        def GetLastUpdateTickAsync(self, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastUpdateTick.invokeAsync(self, ((), context))

        def begin_GetLastUpdateTick(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastUpdateTick.begin(self, ((), _response, _ex, _sent, context))

        def end_GetLastUpdateTick(self, _r):
            return _M_IBTrader.IQDatabase._op_GetLastUpdateTick.end(self, _r)

        def DelCodeId(self, codeId, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_DelCodeId.invoke(self, ((codeId, beginTime, endTime), context))

        def DelCodeIdAsync(self, codeId, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_DelCodeId.invokeAsync(self, ((codeId, beginTime, endTime), context))

        def begin_DelCodeId(self, codeId, beginTime, endTime, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_DelCodeId.begin(self, ((codeId, beginTime, endTime), _response, _ex, _sent, context))

        def end_DelCodeId(self, _r):
            return _M_IBTrader.IQDatabase._op_DelCodeId.end(self, _r)

        def RemoveAllTicks(self, codeId, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllTicks.invoke(self, ((codeId, ), context))

        def RemoveAllTicksAsync(self, codeId, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllTicks.invokeAsync(self, ((codeId, ), context))

        def begin_RemoveAllTicks(self, codeId, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllTicks.begin(self, ((codeId, ), _response, _ex, _sent, context))

        def end_RemoveAllTicks(self, _r):
            return _M_IBTrader.IQDatabase._op_RemoveAllTicks.end(self, _r)

        def RemoveTicksByRange(self, codeId, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveTicksByRange.invoke(self, ((codeId, beginTime, endTime), context))

        def RemoveTicksByRangeAsync(self, codeId, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveTicksByRange.invokeAsync(self, ((codeId, beginTime, endTime), context))

        def begin_RemoveTicksByRange(self, codeId, beginTime, endTime, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveTicksByRange.begin(self, ((codeId, beginTime, endTime), _response, _ex, _sent, context))

        def end_RemoveTicksByRange(self, _r):
            return _M_IBTrader.IQDatabase._op_RemoveTicksByRange.end(self, _r)

        def GetTicks(self, codeId, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetTicks.invoke(self, ((codeId, query), context))

        def GetTicksAsync(self, codeId, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetTicks.invokeAsync(self, ((codeId, query), context))

        def begin_GetTicks(self, codeId, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetTicks.begin(self, ((codeId, query), _response, _ex, _sent, context))

        def end_GetTicks(self, _r):
            return _M_IBTrader.IQDatabase._op_GetTicks.end(self, _r)

        def GetOneTick(self, codeId, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneTick.invoke(self, ((codeId, timePos), context))

        def GetOneTickAsync(self, codeId, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneTick.invokeAsync(self, ((codeId, timePos), context))

        def begin_GetOneTick(self, codeId, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneTick.begin(self, ((codeId, timePos), _response, _ex, _sent, context))

        def end_GetOneTick(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneTick.end(self, _r)

        def UpdateKLine(self, codeId, timeType, kline, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLine.invoke(self, ((codeId, timeType, kline), context))

        def UpdateKLineAsync(self, codeId, timeType, kline, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLine.invokeAsync(self, ((codeId, timeType, kline), context))

        def begin_UpdateKLine(self, codeId, timeType, kline, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLine.begin(self, ((codeId, timeType, kline), _response, _ex, _sent, context))

        def end_UpdateKLine(self, _r):
            return _M_IBTrader.IQDatabase._op_UpdateKLine.end(self, _r)

        def UpdateKLines(self, codeId, timeType, klines, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLines.invoke(self, ((codeId, timeType, klines), context))

        def UpdateKLinesAsync(self, codeId, timeType, klines, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLines.invokeAsync(self, ((codeId, timeType, klines), context))

        def begin_UpdateKLines(self, codeId, timeType, klines, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateKLines.begin(self, ((codeId, timeType, klines), _response, _ex, _sent, context))

        def end_UpdateKLines(self, _r):
            return _M_IBTrader.IQDatabase._op_UpdateKLines.end(self, _r)

        def RemoveAllKLines(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllKLines.invoke(self, ((codeId, timeType), context))

        def RemoveAllKLinesAsync(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllKLines.invokeAsync(self, ((codeId, timeType), context))

        def begin_RemoveAllKLines(self, codeId, timeType, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveAllKLines.begin(self, ((codeId, timeType), _response, _ex, _sent, context))

        def end_RemoveAllKLines(self, _r):
            return _M_IBTrader.IQDatabase._op_RemoveAllKLines.end(self, _r)

        def RemoveKLinesByRange(self, codeId, timeType, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveKLinesByRange.invoke(self, ((codeId, timeType, beginTime, endTime), context))

        def RemoveKLinesByRangeAsync(self, codeId, timeType, beginTime, endTime, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveKLinesByRange.invokeAsync(self, ((codeId, timeType, beginTime, endTime), context))

        def begin_RemoveKLinesByRange(self, codeId, timeType, beginTime, endTime, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveKLinesByRange.begin(self, ((codeId, timeType, beginTime, endTime), _response, _ex, _sent, context))

        def end_RemoveKLinesByRange(self, _r):
            return _M_IBTrader.IQDatabase._op_RemoveKLinesByRange.end(self, _r)

        def RemoveOneKLine(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveOneKLine.invoke(self, ((codeId, timeType, timePos), context))

        def RemoveOneKLineAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveOneKLine.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_RemoveOneKLine(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RemoveOneKLine.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_RemoveOneKLine(self, _r):
            return _M_IBTrader.IQDatabase._op_RemoveOneKLine.end(self, _r)

        def GetKLines(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLines.invoke(self, ((codeId, timeType, query), context))

        def GetKLinesAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLines.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetKLines(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLines.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetKLines(self, _r):
            return _M_IBTrader.IQDatabase._op_GetKLines.end(self, _r)

        def GetOneKLine(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneKLine.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneKLineAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneKLine.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneKLine(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneKLine.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneKLine(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneKLine.end(self, _r)

        def GetKLinePairs(self, first, second, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLinePairs.invoke(self, ((first, second, timeType, query), context))

        def GetKLinePairsAsync(self, first, second, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLinePairs.invokeAsync(self, ((first, second, timeType, query), context))

        def begin_GetKLinePairs(self, first, second, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetKLinePairs.begin(self, ((first, second, timeType, query), _response, _ex, _sent, context))

        def end_GetKLinePairs(self, _r):
            return _M_IBTrader.IQDatabase._op_GetKLinePairs.end(self, _r)

        def GetInvalidKLines(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_GetInvalidKLines.invoke(self, ((codeId, timeType), context))

        def GetInvalidKLinesAsync(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_GetInvalidKLines.invokeAsync(self, ((codeId, timeType), context))

        def begin_GetInvalidKLines(self, codeId, timeType, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetInvalidKLines.begin(self, ((codeId, timeType), _response, _ex, _sent, context))

        def end_GetInvalidKLines(self, _r):
            return _M_IBTrader.IQDatabase._op_GetInvalidKLines.end(self, _r)

        def GetLastDayKLine(self, codeId, msTime, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastDayKLine.invoke(self, ((codeId, msTime), context))

        def GetLastDayKLineAsync(self, codeId, msTime, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastDayKLine.invokeAsync(self, ((codeId, msTime), context))

        def begin_GetLastDayKLine(self, codeId, msTime, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetLastDayKLine.begin(self, ((codeId, msTime), _response, _ex, _sent, context))

        def end_GetLastDayKLine(self, _r):
            return _M_IBTrader.IQDatabase._op_GetLastDayKLine.end(self, _r)

        def RecountAllIndex(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_RecountAllIndex.invoke(self, ((codeId, timeType), context))

        def RecountAllIndexAsync(self, codeId, timeType, context=None):
            return _M_IBTrader.IQDatabase._op_RecountAllIndex.invokeAsync(self, ((codeId, timeType), context))

        def begin_RecountAllIndex(self, codeId, timeType, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_RecountAllIndex.begin(self, ((codeId, timeType), _response, _ex, _sent, context))

        def end_RecountAllIndex(self, _r):
            return _M_IBTrader.IQDatabase._op_RecountAllIndex.end(self, _r)

        def UpdateAllIndexFromTimePos(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateAllIndexFromTimePos.invoke(self, ((codeId, timeType, timePos), context))

        def UpdateAllIndexFromTimePosAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateAllIndexFromTimePos.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_UpdateAllIndexFromTimePos(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_UpdateAllIndexFromTimePos.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_UpdateAllIndexFromTimePos(self, _r):
            return _M_IBTrader.IQDatabase._op_UpdateAllIndexFromTimePos.end(self, _r)

        def GetMas(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetMas.invoke(self, ((codeId, timeType, query), context))

        def GetMasAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetMas.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetMas(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetMas.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetMas(self, _r):
            return _M_IBTrader.IQDatabase._op_GetMas.end(self, _r)

        def GetOneMa(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMa.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneMaAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMa.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneMa(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMa.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneMa(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneMa.end(self, _r)

        def GetVwMas(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetVwMas.invoke(self, ((codeId, timeType, query), context))

        def GetVwMasAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetVwMas.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetVwMas(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetVwMas.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetVwMas(self, _r):
            return _M_IBTrader.IQDatabase._op_GetVwMas.end(self, _r)

        def GetOneVwMa(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneVwMa.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneVwMaAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneVwMa.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneVwMa(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneVwMa.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneVwMa(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneVwMa.end(self, _r)

        def GetEmas(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetEmas.invoke(self, ((codeId, timeType, query), context))

        def GetEmasAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetEmas.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetEmas(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetEmas.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetEmas(self, _r):
            return _M_IBTrader.IQDatabase._op_GetEmas.end(self, _r)

        def GetOneEma(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneEma.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneEmaAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneEma.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneEma(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneEma.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneEma(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneEma.end(self, _r)

        def GetMacds(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetMacds.invoke(self, ((codeId, timeType, query), context))

        def GetMacdsAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetMacds.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetMacds(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetMacds.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetMacds(self, _r):
            return _M_IBTrader.IQDatabase._op_GetMacds.end(self, _r)

        def GetOneMacd(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMacd.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneMacdAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMacd.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneMacd(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneMacd.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneMacd(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneMacd.end(self, _r)

        def GetDivTypes(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetDivTypes.invoke(self, ((codeId, timeType, query), context))

        def GetDivTypesAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetDivTypes.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetDivTypes(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetDivTypes.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetDivTypes(self, _r):
            return _M_IBTrader.IQDatabase._op_GetDivTypes.end(self, _r)

        def GetOneDivType(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneDivType.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneDivTypeAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneDivType.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneDivType(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneDivType.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneDivType(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneDivType.end(self, _r)

        def GetAtrs(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetAtrs.invoke(self, ((codeId, timeType, query), context))

        def GetAtrsAsync(self, codeId, timeType, query, context=None):
            return _M_IBTrader.IQDatabase._op_GetAtrs.invokeAsync(self, ((codeId, timeType, query), context))

        def begin_GetAtrs(self, codeId, timeType, query, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetAtrs.begin(self, ((codeId, timeType, query), _response, _ex, _sent, context))

        def end_GetAtrs(self, _r):
            return _M_IBTrader.IQDatabase._op_GetAtrs.end(self, _r)

        def GetOneAtr(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneAtr.invoke(self, ((codeId, timeType, timePos), context))

        def GetOneAtrAsync(self, codeId, timeType, timePos, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneAtr.invokeAsync(self, ((codeId, timeType, timePos), context))

        def begin_GetOneAtr(self, codeId, timeType, timePos, _response=None, _ex=None, _sent=None, context=None):
            return _M_IBTrader.IQDatabase._op_GetOneAtr.begin(self, ((codeId, timeType, timePos), _response, _ex, _sent, context))

        def end_GetOneAtr(self, _r):
            return _M_IBTrader.IQDatabase._op_GetOneAtr.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IBTrader.IQDatabasePrx.ice_checkedCast(proxy, '::IBTrader::IQDatabase', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IBTrader.IQDatabasePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IBTrader::IQDatabase'
    _M_IBTrader._t_IQDatabasePrx = IcePy.defineProxy('::IBTrader::IQDatabase', IQDatabasePrx)

    _M_IBTrader.IQDatabasePrx = IQDatabasePrx
    del IQDatabasePrx

    _M_IBTrader.IQDatabase = Ice.createTempClass()
    class IQDatabase(Ice.Object):

        def ice_ids(self, current=None):
            return ('::IBTrader::IQDatabase', '::Ice::Object')

        def ice_id(self, current=None):
            return '::IBTrader::IQDatabase'

        @staticmethod
        def ice_staticId():
            return '::IBTrader::IQDatabase'

        def IdlCount(self, current=None):
            raise NotImplementedError("servant method 'IdlCount' not implemented")

        def IsAllIdle(self, current=None):
            raise NotImplementedError("servant method 'IsAllIdle' not implemented")

        def TaskCount(self, current=None):
            raise NotImplementedError("servant method 'TaskCount' not implemented")

        def UpdateTickToDB(self, tick, current=None):
            raise NotImplementedError("servant method 'UpdateTickToDB' not implemented")

        def GetLastUpdateTick(self, current=None):
            raise NotImplementedError("servant method 'GetLastUpdateTick' not implemented")

        def DelCodeId(self, codeId, beginTime, endTime, current=None):
            raise NotImplementedError("servant method 'DelCodeId' not implemented")

        def RemoveAllTicks(self, codeId, current=None):
            raise NotImplementedError("servant method 'RemoveAllTicks' not implemented")

        def RemoveTicksByRange(self, codeId, beginTime, endTime, current=None):
            raise NotImplementedError("servant method 'RemoveTicksByRange' not implemented")

        def GetTicks(self, codeId, query, current=None):
            raise NotImplementedError("servant method 'GetTicks' not implemented")

        def GetOneTick(self, codeId, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneTick' not implemented")

        def UpdateKLine(self, codeId, timeType, kline, current=None):
            raise NotImplementedError("servant method 'UpdateKLine' not implemented")

        def UpdateKLines(self, codeId, timeType, klines, current=None):
            raise NotImplementedError("servant method 'UpdateKLines' not implemented")

        def RemoveAllKLines(self, codeId, timeType, current=None):
            raise NotImplementedError("servant method 'RemoveAllKLines' not implemented")

        def RemoveKLinesByRange(self, codeId, timeType, beginTime, endTime, current=None):
            raise NotImplementedError("servant method 'RemoveKLinesByRange' not implemented")

        def RemoveOneKLine(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'RemoveOneKLine' not implemented")

        def GetKLines(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetKLines' not implemented")

        def GetOneKLine(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneKLine' not implemented")

        def GetKLinePairs(self, first, second, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetKLinePairs' not implemented")

        def GetInvalidKLines(self, codeId, timeType, current=None):
            raise NotImplementedError("servant method 'GetInvalidKLines' not implemented")

        def GetLastDayKLine(self, codeId, msTime, current=None):
            raise NotImplementedError("servant method 'GetLastDayKLine' not implemented")

        def RecountAllIndex(self, codeId, timeType, current=None):
            raise NotImplementedError("servant method 'RecountAllIndex' not implemented")

        def UpdateAllIndexFromTimePos(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'UpdateAllIndexFromTimePos' not implemented")

        def GetMas(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetMas' not implemented")

        def GetOneMa(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneMa' not implemented")

        def GetVwMas(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetVwMas' not implemented")

        def GetOneVwMa(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneVwMa' not implemented")

        def GetEmas(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetEmas' not implemented")

        def GetOneEma(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneEma' not implemented")

        def GetMacds(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetMacds' not implemented")

        def GetOneMacd(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneMacd' not implemented")

        def GetDivTypes(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetDivTypes' not implemented")

        def GetOneDivType(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneDivType' not implemented")

        def GetAtrs(self, codeId, timeType, query, current=None):
            raise NotImplementedError("servant method 'GetAtrs' not implemented")

        def GetOneAtr(self, codeId, timeType, timePos, current=None):
            raise NotImplementedError("servant method 'GetOneAtr' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IBTrader._t_IQDatabaseDisp)

        __repr__ = __str__

    _M_IBTrader._t_IQDatabaseDisp = IcePy.defineClass('::IBTrader::IQDatabase', IQDatabase, (), None, ())
    IQDatabase._ice_type = _M_IBTrader._t_IQDatabaseDisp

    IQDatabase._op_IdlCount = IcePy.Operation('IdlCount', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_int, False, 0), ())
    IQDatabase._op_IsAllIdle = IcePy.Operation('IsAllIdle', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_TaskCount = IcePy.Operation('TaskCount', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), IcePy._t_int, False, 0), ())
    IQDatabase._op_UpdateTickToDB = IcePy.Operation('UpdateTickToDB', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IBTrader._t_ITick, False, 0),), (), None, ())
    IQDatabase._op_GetLastUpdateTick = IcePy.Operation('GetLastUpdateTick', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (((), IcePy._t_int, False, 0), ((), IcePy._t_long, False, 0)), ((), _M_IBTrader._t_ITick, False, 0), ())
    IQDatabase._op_DelCodeId = IcePy.Operation('DelCodeId', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    IQDatabase._op_RemoveAllTicks = IcePy.Operation('RemoveAllTicks', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())
    IQDatabase._op_RemoveTicksByRange = IcePy.Operation('RemoveTicksByRange', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    IQDatabase._op_GetTicks = IcePy.Operation('GetTicks', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_ITicks, False, 0),), None, ())
    IQDatabase._op_GetOneTick = IcePy.Operation('GetOneTick', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_ITick, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_UpdateKLine = IcePy.Operation('UpdateKLine', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IKLine, False, 0)), (), None, ())
    IQDatabase._op_UpdateKLines = IcePy.Operation('UpdateKLines', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IKLines, False, 0)), (), None, ())
    IQDatabase._op_RemoveAllKLines = IcePy.Operation('RemoveAllKLines', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0)), (), None, ())
    IQDatabase._op_RemoveKLinesByRange = IcePy.Operation('RemoveKLinesByRange', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    IQDatabase._op_RemoveOneKLine = IcePy.Operation('RemoveOneKLine', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    IQDatabase._op_GetKLines = IcePy.Operation('GetKLines', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IKLines, False, 0),), None, ())
    IQDatabase._op_GetOneKLine = IcePy.Operation('GetOneKLine', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IKLine, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetKLinePairs = IcePy.Operation('GetKLinePairs', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IKLinePairs, False, 0),), None, ())
    IQDatabase._op_GetInvalidKLines = IcePy.Operation('GetInvalidKLines', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0)), (((), _M_IBTrader._t_IKLines, False, 0),), None, ())
    IQDatabase._op_GetLastDayKLine = IcePy.Operation('GetLastDayKLine', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IKLine, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_RecountAllIndex = IcePy.Operation('RecountAllIndex', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0)), (), None, ())
    IQDatabase._op_UpdateAllIndexFromTimePos = IcePy.Operation('UpdateAllIndexFromTimePos', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (), None, ())
    IQDatabase._op_GetMas = IcePy.Operation('GetMas', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IAvgValues, False, 0),), None, ())
    IQDatabase._op_GetOneMa = IcePy.Operation('GetOneMa', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IAvgValue, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetVwMas = IcePy.Operation('GetVwMas', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IAvgValues, False, 0),), None, ())
    IQDatabase._op_GetOneVwMa = IcePy.Operation('GetOneVwMa', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IAvgValue, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetEmas = IcePy.Operation('GetEmas', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IAvgValues, False, 0),), None, ())
    IQDatabase._op_GetOneEma = IcePy.Operation('GetOneEma', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IAvgValue, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetMacds = IcePy.Operation('GetMacds', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IMacdValues, False, 0),), None, ())
    IQDatabase._op_GetOneMacd = IcePy.Operation('GetOneMacd', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IMacdValue, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetDivTypes = IcePy.Operation('GetDivTypes', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IDivTypeValues, False, 0),), None, ())
    IQDatabase._op_GetOneDivType = IcePy.Operation('GetOneDivType', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IDivTypeValue, False, 0),), ((), IcePy._t_bool, False, 0), ())
    IQDatabase._op_GetAtrs = IcePy.Operation('GetAtrs', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), _M_IBTrader._t_IQuery, False, 0)), (((), _M_IBTrader._t_IAtrValues, False, 0),), None, ())
    IQDatabase._op_GetOneAtr = IcePy.Operation('GetOneAtr', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), _M_IBTrader._t_ITimeType, False, 0), ((), IcePy._t_long, False, 0)), (((), _M_IBTrader._t_IAtrValue, False, 0),), ((), IcePy._t_bool, False, 0), ())

    _M_IBTrader.IQDatabase = IQDatabase
    del IQDatabase

# End of module IBTrader
