# config/strategies.yaml
strategies:
  - name: "NQ_Trend_Long_V1"
    class: "DoubleMAStrategy"   # [新增] 明确指定要实例化的类名
    enable: true
    symbol: "NQ"
    interval: "D1"
    start_time: "2025-01-01 00:00:00"
    end_time: "2026-01-01 00:00:00"
    direction_limit: "LONG"
    params:
      fast_window: 5
      slow_window: 20

  - name: "NQ_Trend_Short_V1"
    class: "DoubleMAStrategy"   # 同样的类，不同的实例名称和参数
    enable: false
    symbol: "NQ"
    interval: "M15"
    start_time: "2025-01-01 00:00:00"
    end_time: "2026-01-01 00:00:00"
    direction_limit: "SHORT"
    params:
      fast_window: 10
      slow_window: 40